// gitprofile.config.js

module.exports = {
  fullName: "Yesun-Erdene Jargalsaikhan",
  profession: "Software Engineer",
  occupation: "6 years in Mobile app development",
  // description:
  //   "I am a proactive Software Engineer and MSc Computer Science candidate with over 5 years of proficient experience in mobile application project development. My expertise spans software engineering, machine learning, and deep learning, with hands-on experience training language and vision models during my master’s studies.\n\nI have developed and published dozen of mobile applications that are widely used in my country and abroad.\n I would like to work on projects that could leverage my knowledge in software development and machine learning integrated applications.",
  description: [
    "I'm a Software Engineer with MSc Computer Science with over 6 years of proficient experience in full-lifecycle mobile application development and publication.",
    "My expertise spans software engineering, machine learning, and deep learning.",
    "During my master’s studies, I gained hands-on experience on training, evaluating, and optimizing language and vision models, building a strong foundation in ML workflows.",
    "I have developed and published dozens of widely used mobile applications both nationally and internationally.",
    "I am seeking roles where I can leverage my software development skills and learn more in integrating machine learning models with applications.",
  ],
  d: "",

  contact: [
    {
      key: "Email",
      icon: "fa-regular fa-envelope",
      url: false,
      value: "yesunerdenej@gmail.com",
      href: "#",
    },
    // {
    //   key: "Phone",
    //   icon: "fa-solid fa-mobile",
    //   url: false,
    //   value: "+976 99401008",
    //   href: "#",
    // },
    // {
    //   key: "Phone",
    //   icon: "fa-solid fa-mobile",
    //   url: false,
    //   value: "+39 345 527 1173",
    //   href: "#",
    // },
    {
      key: "WhatsApp",
      icon: "fa-brands fa-whatsapp",
      url: false,
      value: "+39 345 527 1173",
      href: "#",
    },
    {
      key: "LinkedIn",
      icon: "fa-brands fa-linkedin",
      url: true,
      value: "https://www.linkedin.com/in/yesunerdene-jargalsaikhan-b46398162/",
      href: "https://www.linkedin.com/in/yesunerdene-jargalsaikhan-b46398162/",
    },
    {
      key: "GitHub",
      icon: "fa-brands fa-github",
      url: true,
      value: "https://github.com/yesunerdene9",
      href: "https://github.com/yesunerdene9",
    },
    // {
    //   key: "Facebook",
    //   icon: "fa-brands fa-facebook",
    //   url: true,
    //   value: "https://www.facebook.com/Yesunerdene9",
    //   href: "https://www.facebook.com/Yesunerdene9",
    // },
  ],
  educations: [
    {
      href: "https://www.unitn.it/en",
      university: "University of Trento, Italy 🇮🇹",
      department: "Department of Information Engineering and computer science",
      thesis: "Knowledge-Based Concept Token Embeddings for Language Models",
      thesisDescription:
        "Based on the thesis, I developed a mobile application and a website for a real estate selling, renting, purchasing and auctioning platform.",
      grade: "109/110",
      major: "MSc in Computer Science",
      degree: "Bachelor",
      // from: "Sep 2023",
      // to: "Mar 2026",
      from: "09/2023",
      to: "03/2026",
      techs: [
        "Machine Learning",
        "Deep Learning",
        "Applied NLP",
        "Natural Language Understanding",
        "Computer Vision",
        "Data Visualization",
        "Knowledge Graph Engineering",
        "Advanced Human Computer Interaction",
        "Computability and Computational Complexity",
      ],
      scholarships: "Master's Scholarship (Fully Funded)",
    },
    {
      href: "https://portal.num.edu.mn/en/",
      university: "National University of Mongolia 🇲🇳",
      department:
        "\nSchool of Engineering and Applied Science, (Department of Information and Computer Science)",
      thesis:
        "Development of Real Estate Advertisement platform Based on a Map  (Web & Mobile Application)",
      thesisDescription:
        "Based on the thesis, I developed a mobile application and a website for a real estate platform.",
      grade: "3.5 / 4.0",
      major: "BEng in Software Engineering",
      degree: "Bachelor",
      // from: "Sep 2016",
      // to: "Jun 2020",
      from: "09/2016",
      to: "06/2020",
      techs: [
        "Programming",
        "Algorithm design and analysis",
        "Data structures",
        "Software architecture and Design",
        "Software Development",
        "Web Programming",
        "Computer graphics",
        "Mobile application Development",
        "Operating Systems",
        "Software quality and testing",
        "Software Requirement Analysis",
      ],
    },
  ],
  technologies: [
    {
      language: "Languages",
      techs: [
        "Python",
        "Javascript",
        "Typescript",
        "Java",
        "PHP",
        "C++",
        "SQL",
        "SPARQL",
        "GraphQL",
      ],
    },
    {
      language: "Software Engineering",
      techs: [
        "React NativeJS",
        "ReactJS",
        "RESTApi",
        "Websoket",
        "PHP Symfony",
        "NodeJS",
        "AngularJS",
        "Firebase",
        "MySQL",
        "PostregSQL",
      ],
    },
    {
      language: "Mobile App Development",
      techs: [
        "Redux",
        "Redux-Saga",
        "React-Navigation",
        "Context",
        "Zustand",
        "Axios",
        "Third Party Libraries",
        "Animation",
        "State Management",
        "Push Notifications",
        "Socket",
        "Data visualization",
      ],
    },
    {
      language: "Machine Learning",
      techs: [
        "PyTorch",
        "Machine Learning",
        "Deep Learning",
        "Applied NLP",
        "Computer Vision",
        "Data engineering and visualization",
        "Knowledge Graphs",
      ],
    },
    {
      language: "Tools",
      techs: [
        "AppStoreConnect",
        "TestFlight",
        "Google Play Console",
        "Git",
        "Docker",
        "AWS",
        "HotUpdates",
      ],
    },
    {
      language: "Language",
      techs: ["English C1", "Italian A2"],
    },
  ],
  experiences: [
    {
      company: "DataScientia research community at University of Trento",
      position: "Fellow Researcher",
      // from: "Sep 2025",
      from: "04/2026",
      to: "Present",
      href: "https://datascientia.disi.unitn.it/",
      // href: "http://knowdive.disi.unitn.it/",
      description:
        "Working on developing the website of UKC, and maintenance of importing new language and concepts to the UKC lexical database. Also developed a mobile application for collecting data from users to improve the knowledge graph of UKC.",
      techs: [
        "AngularJS",
        "Python",
        "Docker",
        "NodeJs",
        "Mongo",
        "React Native",
        "JKAN",
        "Java",
      ],
    },
    {
      company: "Alpha Labs LLC",
      position: "Software Developer (remote)",
      // from: "Jul 2020",
      // to: "Sep 2025",
      from: "07/2023",
      to: "01/2026",
      href: "https://www.alphalabs.mn/",
      description:
        "Alpha Labs LLC is a technology company founded in January 2015 and conducts the development of various kinds of platforms. \n\n I have been working as a software engineer, especially in the mobile application development of BSB.MN, G-Power monitoring and ISU Mongolia. I take responsibility in whole projects of the mobile applications respectively, in which I do project planning, designing, developing, testing and maintaining the app.",
      techs: [
        "React NativeJS",
        "Firebase",
        "AWS",
        "Typescript",
        "Google Cloud",
      ],
    },
    {
      company: "Powered LLC",
      position: "Senior Software Engineer",
      // from: "Jan 2022",
      from: "01/2022",
      to: "08/2023",
      href: "https://powered.mn/",
      description:
        "Powered LLC is a technology company founded in December 2021 which runs the Octagon - a crypto-based NFT marketplace and crypto exchange platform. \n\n I had worked as a software engineer, especially in the mobile application development of the Octagon app, which includes features of a digital wallet control, a crypto exchange and an NFT marketplace. As a developer, I take responsibility for the whole mobile application project, which I do project planning, designing, developing, testing and maintaining the app.",

      techs: ["React NativeJS", "Firebase", "Typescript"],
    },
    // {
    //   company: "Powered LLC",
    //   position: "Software developer (remote)",
    //   from: "Jan 2021",
    //   to: "Jan 2022",
    //   href: "https://powered.mn/",
    //   description:
    //     "Powered LLC is a technology company founded in January 2021 which runs the YESH.MN - test- based learning app for university general entrance examination for high school students.\n\n I have been working as a software engineer, especially in the mobile application development of YE SH.MN app, which includes features for taking a test of entrance exam. I take responsibility for the whole mobile application project, which involves project planning, designing, developing, testing and maintaining the app.",
    //   techs: ["React NativeJS", "Firebase", "Typescript"],
    // },
    {
      company: "Digital Mall LLC / And Global",
      position: "Software Engineer",
      // from: "Sep 2019",
      // to: "Jan 2022",
      from: "09/2019",
      to: "01/2022",
      href: "https://and.global/",
      description:
        "Digital Mall LLC is a technology company founded in June 2019 which runs the BananaMall - an e- commerce platform that for online shopping with delivery service.\n\nAt the beginning of my 4th year of study in software engineering, my former internship employer company offered me to work as a software developer in their e-commerce system. As a part of the development team, I worked as a software engineer, especially in the development of the mobile application, core backend development, and admin panel of the e-commerce platform, and took responsibility for database engineering.",
      techs: [
        "React NativeJS",
        "React JS",
        "PHP Symfony",
        "ReactJS",
        "MySQL",
        "Firebase",
      ],
    },
  ],
  webs: [
    {
      id: 0,
      title: "BananaMall",
      company: "Digital Mall LLC",
      role: "Software engineer",
      releasedOn: "Jun 2020",
      link: "https://bananamall.mn",
      logo: require("./assets/bananamall.png"),
      techs: ["ReactJS", "MySQL", "PHP Symfony", "AWS"],
      desc: "An e-commerce website.",
    },
    {
      id: 1,
      title: "UKC",
      company: "DataScientia",
      role: "Researcher & ML engineer",
      releasedOn: "08/2017",
      link: "https://ukc.datascientia.eu",
      logo: require("./assets/ukc.png"),
      techs: [
        "AngularJs",
        "Java",
        "Python",
        "NodeJs",
        "MongoDB",
        "Docker",
        "PostgreSQL",
        "JKAN",
      ],
      desc: "I worked on developing a web application of Universal Knowledge Core, where huge, high-quality, human-curated multilingual lexical database can be explored.",
    },
    {
      id: 1,
      title: "Togloom Trade",
      company: "Ocurus.mn / And Global LLC",
      role: "Web developer",
      releasedOn: "09/2019",
      link: "https://togloom.trade",
      logo: require("./assets/togloom.png"),
      techs: ["PHP", "PHP Laravel", "MySQL"],
      desc: "I developed a website for an e-sport game virtual item marketplace.",
    },
  ],
  projects: [
    {
      type: "E-commerce",
      techs: ["React NativeJS", "Typescript", "Javascript", "Firebase"],
      items: [
        {
          id: 5,
          title: "100ail market",
          company: "Alpha Labs LLC",
          role: "Mobile app developer",
          releasedOn: "Jan 2024",
          appStore: "https://apps.apple.com/gr/app/100-ail-market/id6469462088",
          playStore:
            "https://play.google.com/store/apps/details?id=com.hundredailmarket.mobileapp",
          logo: require("./assets/ail.png"),
          techs: ["React NativeJs"],
          desc: "I developed a mobile application for all trade centres of building materials in Mongolia to make their trade online. It is an e-commerce application where shop sellers register their products, and buyers purchase their needs online. Also, delivery service companies handle user orders through the application. (React Native JS)",
        },
        {
          id: 3,
          title: "BSB.mn",
          company: "Alpha Labs LLC",
          role: "Mobile app developer",
          releasedOn: "Oct 2021",
          appStore: "https://apps.apple.com/mn/app/bsb-mn/id1550545343",
          playStore:
            "https://play.google.com/store/apps/details?id=com.bsb.mobileapp",
          logo: require("./assets/bsb.png"),
          techs: ["React NativeJs"],
          desc: "I developed the mobile application of BSB.MN for e-commerce of online shopping and delivery service (React Native JS).",
        },
        {
          id: 2,
          title: "Banana Mall",
          company: "Digital Mall LLC",
          role: "Software engineer",
          releasedOn: "Nov 2021",
          appStore: "https://apps.apple.com/ca/app/bananamall/id1562615154",
          playStore:
            "https://play.google.com/store/apps/details?id=com.bananamall",
          logo: require("./assets/bananamall.png"),
          techs: ["React NativeJs"],
          desc: "An e-commerce platform for selling and delivering products online. As a developer, I worked on the following: \n1. Mobile application of the e-commerce (React Native JS)\n2. Core back-end of the e-commerce platform (Symfony PHP)\n3. Admin panel of the e-commerce back-office (React JS)\n4. Database support engineering (SQL)",
        },
        {
          id: 6,
          title: "Taiki",
          // company: "Alpha Labs LLC",
          role: "Mobile app developer",
          releasedOn: "2024",
          appStore:
            "https://apps.apple.com/it/app/taiki-%D0%B2%D0%B0%D1%88-%D1%86%D0%B5%D0%BD%D1%82%D1%80-%D1%88%D0%BE%D0%BF%D0%BF%D0%B8%D0%BD%D0%B3%D0%B0/id6504776266?l=en-GB",
          playStore:
            "https://play.google.com/store/apps/details?id=com.taiki&hl=en",
          logo: require("./assets/taiki.png"),
          techs: ["React NativeJs"],
          desc: "I developed a mobile application dedicated to citizens of Kazakhstan for purchasing products from China. (React Native TS)",
        },
        {
          id: 7,
          title: "Suvd",
          // company: "Alpha Labs LLC",
          role: "Mobile app developer",
          releasedOn: "2025",
          appStore: "https://apps.apple.com/us/app/suvd-online/id6741729989",
          playStore:
            "https://play.google.com/store/apps/details?id=com.boloroutlet",
          logo: require("./assets/suvd.png"),
          techs: ["React NativeJs"],
          desc: "I developed a mobile application dedicated to citizens of Mongolians for purchasing products from Korea. (React Native TS)",
        },
      ],
    },
    {
      type: "Education",
      items: [
        {
          id: 1,
          title: "YESH.MN",
          company: "Powered LLC",
          role: "Mobile app developer",
          releasedOn: "May 2021",
          appStore: "https://apps.apple.com/mn/app/yesh-mn/id1556433230",
          playStore: "https://play.google.com/store/apps/details?id=com.yesh",
          logo: require("./assets/yesh.png"),

          techs: ["React NativeJs"],
          desc: "I developed a mobile application for YESH.MN - test-based learning mobile application for high school students preparing for the university general entrance examination. The application has a testing feature, which lets users take a test of all kinds of high school subjects with various sorts of testing types and show the result with correct answers and theories to review. It also has the feature of helping to choose a profession for students. About 50 per cent of examinees use this application in the corresponding year to prepare for the examination (React Native JS).",
        },
        {
          id: 1,
          title: "YESH.MN v2",
          company: "Powered LLC",
          role: "Mobile app developer",
          releasedOn: "May 2021",
          appStore: "https://apps.apple.com/mn/app/yesh-mn/id1556433230",
          playStore: "https://play.google.com/store/apps/details?id=com.yesh",
          logo: require("./assets/yesh2.png"),
          techs: ["React NativeJs"],
          desc: "I developed a mobile application for YESH.MN - test-based learning mobile application for high school students preparing for the university general entrance examination. The application has a testing feature, which lets users take a test of all kinds of high school subjects with various sorts of testing types and show the result with correct answers and theories to review. It also has the feature of helping to choose a profession for students. About 50 per cent of examinees use this application in the corresponding year to prepare for the examination (React Native JS).",
        },
        {
          id: 5,
          title: "ISU Mongolia",
          // company: "Alpha Labs LLC",
          role: "Mobile app developer",
          releasedOn: "coming soon",
          appStore: "",
          playStore: "",
          techs: ["React NativeJs"],
          logo: require("./assets/isu.jpeg"),
          desc: 'I developed a mobile portal application dedicated to employees and parents of students of the "International School of Ulaanbaatar" for managing various kinds of activity in the school (React Native JS).',
        },
        {
          id: 8,
          title: "iLogg",
          // company: "Alpha Labs LLC",
          role: "Mobile app developer",
          releasedOn: "coming soon",
          appStore: "https://apps.apple.com/it/app/ilogg/id1579007486?l=en-GB",
          playStore: "",
          techs: ["React NativeJs"],
          logo: require("./assets/ilog.png"),
          desc: 'I developed a mobile portal application dedicated to employees and parents of students of the "International School of Ulaanbaatar" for managing various kinds of activity in the school (React Native JS).',
        },
        {
          id: 1,
          title: "Drivintest MN",
          company: "Powered LLC",
          role: "Mobile app developer",
          releasedOn: "May 2021",
          appStore: "https://apps.apple.com/mn/app/yesh-mn/id1556433230",
          playStore: "https://play.google.com/store/apps/details?id=com.yesh",
          logo: require("./assets/drivingtest.png"),

          techs: ["React NativeJs"],
          desc: "Mobile application for preparing the driving theory test exam. Has varius functions for preparing the exam and analysing results.",
        },
      ],
    },
    {
      type: "Crypto & Wallet",
      items: [
        {
          id: 0,
          title: "Octagon Wallet",
          company: "Octagon LLC",
          role: "Mobile app developer",
          releasedOn: "Mar 2022",
          appStore: "https://apps.apple.com/mn/app/octagon-wallet/id1611280720",
          playStore:
            "https://play.google.com/store/apps/details?id=com.octagonwallet.mobile",
          logo: require("./assets/octagon.png"),
          techs: ["React NativeJs"],
          desc: "I developed a mobile application for Octagon Ecosystem - a crypto exchange market, NFT marketplace, and digital wallet. It has broad features, such as a virtual asset market, a virtual ticket utility, awarded competitions and more (React Native Js).",
        },
        {
          id: 4,
          title: "Walk & Earn",
          company: "Octagon LLC",
          role: "Mobile app developer",
          releasedOn: "Dec 2022",
          appStore: "https://apps.apple.com/mn/app/and-walk-earn/id1665115756",
          playStore:
            "https://play.google.com/store/apps/details?id=com.walkandearn.mobileapp",
          logo: require("./assets/and.png"),
          techs: ["React NativeJs"],
          desc: "I developed a mobile application for the statistics on the walking of the whole national citizens. It works like a pedometer and rewards the person who reaches the targeted number of steps (React Native JS). ",
        },
      ],
    },
    {
      type: "Monitoring",
      items: [
        {
          id: 6,
          title: "G-Solar",
          // company: "Alpha Labs LLC",
          role: "Mobile app developer",
          releasedOn: "coming soon",
          appStore: "",
          playStore:
            "https://play.google.com/store/apps/details?id=com.gpower.mobile",
          logo: require("./assets/gpower.png"),
          techs: ["React NativeJs"],
          desc: 'I developed a mobile application for the clients of a power supply company named "Gpower" for monitoring and surveillance of power consumption of their activity (React Native JS).',
        },
      ],
    },
  ],
  mlprojects: [
    {
      id: 0,
      title:
        "Analysing archer's body posture with MoCap to detect incorrect posture",
      type: "Computer Vision",
      from: "Feb 2024",
      to: "Sep 2025",
      href: "https://github.com/yesunerdene9/computer-vision",
      description:
        "This project analyses the fundamental body posture of an archer using MoCap technology to capture key postural parameters such as joint angles and foot distances. The aim is to provide insights that could lead to an automatic method for evaluating posture and classifying it as proper or incorrect in future work. The result of the analysis highlights a significant difference between the reference correct and incorrect body postures, showing the potential for objective classification based on measurable postural features.",
      techs: ["Python"],
      embed: "https://www.youtube.com/embed/yhi8Jw9u4aQ",
    },
    {
      id: 1,
      title: "Test Time Adaptation with MEMO",
      type: "Deep Learning",
      from: "Feb 2024",
      to: "Sep 2025",
      href: "https://github.com/yesunerdene9/deep-learning",
      description:
        "In this project I re-implemented Zhang et al. (2021) MEMO (Marginal Entropy Minimization with One test point) to improve the performance of the pre-trained model on image classification task at a test time. The purpose of the project is to adapt the model to perform better when the test data distribution differs from the distribution of the dataset it was originally trained on.",
      techs: ["Pytorch", "Imagenet"],
    },
    {
      id: 2,
      title: "Interpreting Sign Language Letters",
      type: "Multisensory Interactive Systems",
      from: "Feb 2024",
      to: "Sep 2025",
      href: "https://github.com/yesunerdene9/deep-learning",
      description:
        "With my team built a system that recognizes six American Sign Language (ASL) alphabet gestures using a sensor-equipped glove, an Arduino Uno, and a combination of Processing and Pure Data. ",
      techs: [
        "Pure Data",
        "Arduino",
        "Java",
        "Processing",
        "Electric circles",
        "Flex sensors",
      ],
      embed:
        "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7287434924108791808?collapsed=1",
    },
  ],
  certificates: [
    {
      org: "ITPEC",
      title: "FUNDAMENTAL INFORMATION TECHNOLOGY ENGINEER EXAMINATION",
      text: "Certified Information Technology Professional (FE)",
      year: "2019",
      number: "MNFE18A0009",
      link: "https://itpec.org/statsandresults/all-passers-information/Mongolia/2019A_FE.pdf",
    },
    {
      org: "ITPEC",
      title: "INFORMATION TECHNOLOGY PASSPORT EXAMINATION",
      text: "Certified Information Technology Professional (IP)",
      year: "2018",
      number: "MNIP18A0009",
      link: "https://itpec.org/statsandresults/all-passers-information/Mongolia/2018A_IP.pdf",
    },
  ],
  github: {
    username: "Yesunerdene", // Your GitHub org/user name. (Required)
    sortBy: "stars", // stars | updated
    limit: 100, // How many projects to display.
    exclude: {
      forks: false, // Forked projects will not be displayed if set to true.
      projects: [], // These projects will not be displayed. example: ['my-project1', 'my-project2']
    },
  },
  social: {
    linkedin:
      "https://www.linkedin.com/in/yesunerdene-jargalsaikhan-b46398162/",
    twitter: "",
    facebook: "https://www.facebook.com/Yesunerdene9",
    instagram: "https://www.instagram.com/yesunerdene9",
    whatsapp: "+39 3455271173",
    dribbble: "",
    behance: "",
    medium: "",
    dev: "",
    website: "",
    phone: "+976 96891008",
    email: "yesuuygls@gmail.com",
  },
};
